swagger: "2.0"
info:
  version: "1.0.0"
  title: vod-ms-upgrade-journey-authentication
tags:
  - name: Checkout Authentication
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /rest/services/v1/apps/checkout-auth/customers/{idNumber}/msisdn:
    get:
      tags:
        - "Checkout Authentication"
      operationId: getMsisdnList
      consumes:
        - application/json
      parameters:
        - in: path
          name: idNumber
          type: string
          required: true
        - in: query
          name: docType
          type: string
          required: true
      responses:
        200:
          description: Success
          schema:
            $ref: "#/definitions/MsisdnList"
        400:
          description: Missing required input parameter
        401:
          description: Not authorized
        424:
          description: Upstream call failed with a 500. Response will be identical to upstream failure
        500:
          description: Technical error occured, service failure.
  /swagger:
    x-swagger-pipe: swagger_raw

# complex objects have schema definitions
definitions:
  MsisdnList:
    type: object
    properties:
      messages:
        type: array
        items:
          type: string
      result:
        type: array
        items:
          type: string